language: node_js
node_js:
  - '8'
  - '10'
  - lts/*
  - node

matrix:
  include:
    - node_js: '6'
      env: NO_LINT=true

script:
  - if [[ -z "${NO_LINT}" ]]; then npm run lint; fi
  - npm run build
  - npm test
